### ISSUE TITLE
Embarking on the same project - share experience?

### ISSUE THREAD

**Issue by alesanmanoweb** [ayavilevich/rinnai-wifi#1]
Hello Mr. Arik,
I was about to connect an oscilloscope to my Rinnai heater when I discovered your repository thanks to a comment on a [Stack Exchange question](https://electronics.stackexchange.com/questions/512442/rinnai-water-heater-power-and-communication-interface-protocol). I believe we are trying to do something quite similar - bypass the Rinnai proprietary devices to control the heater and use an ESP32 to provide a sane interface that actually works. Let me know if you would be interested to share some experience, I have several questions at this point.

**Comment by ayavilevich** [comment]
Hey Alessio,

That is awesome. I am very close to finishing the article about my project. The code works as well as the device that I added to my installation.
Thanks for sharing the link to the SE question. LMK what questions you have. I can answer them here.

If you are willing, I am interested to get good quality photos of the PCB of your device. By device I mean the control panel or Control-R. I strongly suggest not to mess with the main heater itself. I am also interested to get captures of the data buses to compare and try to understand if there are differences between the different models.

Are you mainly software or electronics oriented? At what level?

**Comment by alesanmanoweb** [comment]
Hello, I am mainly an embedded software developer but I often deal with the EE stuff. So far my experience is that the wifi module + app are not an acceptable solution, it's cumbersome and simply does not work for my use case. I am open to evaluate different solutions and see how they fit in my use case

**Comment by alesanmanoweb** [comment]
Regarding photos, are the ones referenced in the SE question not good enough? This is the direct link to the imgur album https://imgur.com/a/5WT6Dzk

**Comment by ayavilevich** [comment]
The photos are helpful but some important areas are not visible (too dark). We should focus on the area between the daughter board and the MCU. Please trace the pins of the daughter board and make a list of where they connect to at depth of two levels.

Here is the most interesting area IMO: https://i.imgur.com/O8KZMeW.jpg . I also makred with red the dark area where it is not possible to see the traces/vias clearly.

Here is a photo of the PCB of a non wifi Rinnai control panel. https://imgur.com/gallery/4cNFOh8
See the area with IFT1 and IC2. I believe the potted daughter board contains this region or one equivalent.

**Comment by alesanmanoweb** [comment]
Continuing on discord
